### ISSUE TITLE
Auto-Compile and Auto-Reload of Electron/

### ISSUE THREAD

**Issue by drixie** [maxstue/vite-reactts-electron-starter#20]
Hello, 

Thank you so much for putting this template together. I am new to Electron and this has been super helpful in getting up to speed. 

I noticed that auto-reload is very easy on the Renderer process, but I have to restart "yarn dev" everytime I make changes to code in the electron/ folder (index.ts and preload.ts). Is there any way to have these files auto-compile into JS and auto-reload every time I save the files? If this is not possible, what command can I run in a separate terminal while having to "CTRL+C and yarn dev"? Can I use nodemon to handle this? 

Thanks in advance

**Comment by maxstue** [comment]
This repo just has a very simple project setup and I agree the hot reload for the electron code is missing. But because of it missing I am referencing to more advanced repositories in the Readme. 
There are templates having HMR.[Link](https://github.com/maxstue/vite-reactts-electron-starter#more-advanced-templates)
