### ISSUE TITLE
Uncaught ReferenceError: __dirname is not defined

### ISSUE THREAD

**Issue by Sgout-Li** [maxstue/vite-reactts-electron-starter#5]
![image](https://user-images.githubusercontent.com/50992790/125749706-331b3255-1410-4f49-adfb-0f7ac631d083.png)

**Comment by maxstue** [comment]
Can you please explain how and what code causes the problem and how to reproduce it?

Do u have a public repo? Than I can check it out

**Comment by maxstue** [comment]
@Sgout-Li There was a new PR merged, check out if the problem still occures and please give some feedback in here :)

**Comment by eai04191** [comment]
This problem is still going on. Just import ipcRenderer and put it in console.log as shown in the screenshot.

![2021-07-30_16-20-52](https://user-images.githubusercontent.com/3516343/127616437-43a75221-0a52-4e6b-8864-bd5cd76b277a.png)

changes: https://github.com/eai04191/vite-reactts-electron-starter/commit/32a9cca1e0f12054de71603e2c24139e205c1aba

**Comment by maxstue** [comment]
@eai04191 @Sgout-Li  This should now be fixed an the main brnach. 

> But be aware it is not the safest way and you should use the [contextIsolation ](https://www.electronjs.org/docs/tutorial/context-isolation#security-considerations)
